import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../../styles/Home.module.css'
import Card from '../Card'

const Versus: NextPage = () => {
  const [widthScreen, setWidthScreen] = useState(0);

  useEffect(() => {
    setWidthScreen(window.innerWidth);
  }, [])
  
    return (
        <div className={styles.container} style={{ backgroundImage:  "url('/images/background-party.jpg')"}}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <span style={{ fontSize: '150px', fontWeight: 'bold' }}>LET'S FIGHT !</span>

                <div className="container py-5 mx-0 mw-100">
                  <Card value={5} canClose={false} />
                </div>
            </main>

            <footer className={styles.footer}>

            </footer>
        </div>
    )
}

export default Versus
