import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";

const Help: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="container py-5 mx-0 mw-100">
          <div className={styles.landingText}>
            <div className="row d-flex justify-content-center mb-5">
              <h1 className={styles.title}>Welcome to Poker Fight !</h1>
            </div>

            <div className="row d-flex justify-content-center pt-5">
              <div className="col-sm-4">
                <h2>Doc Bootstrap Grid</h2>
              </div>
              <div className="col-sm-2">
                <div className="row">
                  <input
                    type="button"
                    className="btn btn-primary"
                    value="Ici"
                    onClick={() =>
                      (location.href =
                        "https://getbootstrap.com/docs/5.1/layout/grid/")
                    }
                  />
                </div>
              </div>
            </div>
            <div className="row d-flex justify-content-center pt-5">
              <div className="col-sm-4">
                <h2>Doc Flexbox</h2>
              </div>
              <div className="col-sm-2">
                <div className="row">
                  <input
                    type="button"
                    className="btn btn-primary"
                    value="Ici"
                    onClick={() =>
                      (location.href =
                        "https://css-tricks.com/snippets/css/a-guide-to-flexbox/")
                    }
                  />
                </div>
              </div>
            </div>
            <div className="row d-flex justify-content-center pt-5">
              <div className="col-sm-4">
                <h2>Doc Next JS</h2>
              </div>
              <div className="col-sm-2">
                <div className="row">
                  <input
                    type="button"
                    className="btn btn-primary"
                    value="Ici"
                    onClick={() => (location.href = "https://nextjs.org/docs")}
                  />
                </div>
              </div>
            </div>
            <div className="row d-flex justify-content-center pt-5">
              <div className="col-sm-4">
                <h2>Doc React TS Hooks</h2>
              </div>
              <div className="col-sm-2">
                <div className="row">
                  <input
                    type="button"
                    className="btn btn-primary"
                    value="Ici"
                    onClick={() =>
                      (location.href =
                        "https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/hooks/")
                    }
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Help;
