steps:
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        cp known_hosts.github /root/.ssh/known_hosts
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  - name: 'gcr.io/cloud-builders/git'
    args: [ 'fetch', '--unshallow', 'git@github.com:5thfloor-luva/poker-fight' ]
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: '/bin/sh'
    args:
      - -c
      - git rev-list --count master && echo $(git rev-list --count master) > VERSION
    volumes:
      - name: 'ssh'
        path: /root/.ssh
  - name: 'npm'
    id: 'npm build'
    entrypoint: 'bash'
    args:
      - -c
      - ./npm run build
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build docker image'
    entrypoint: '/bin/sh'
    dir: 'api'
    args:
      - -c
      - docker build -t ${_DOCKER_IMAGE}:$(cat /workspace/VERSION) .
options:
  substitution_option: 'ALLOW_LOOSE'
  machineType: 'E2_HIGHCPU_8'
availableSecrets:
  secretManager:
    - versionName: projects/poker-fight/secrets/github-secret/versions/latest
      env: 'SSH_KEY'

