import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Button, Col, Container, Row } from 'react-bootstrap';
import styles from '../styles/Home.module.css';
import { MdAccountCircle } from 'react-icons/md'

const Header: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <Container>
        <Row className='pt-3 d-flex align-items-center'>
          <Col xs="3" className="d-flex align-content-sm-start">
            <div>
              <Image objectFit='fill' src='/images/logo-project.png' width={300} height={60} alt="logo" />
            </div>
          </Col>
          <Col xs="4" className="d-flex align-items-center justify-content-center">
            <Row>
              <Col>
                <div>
                  <input className='rounded-5' />
                </div>
              </Col>
              <Col>
                <div>
                  <Button className='rounded-5 p-1' >Copy</Button>
                </div>
              </Col>
            </Row>
          </Col>
          <Col xs="3">
            <div className='align-content-center text-center pt-3'>
              <p className='bg-success border rounded-pill text-white fw-bolder' >Nombre de points: 20/60</p>
            </div>

          </Col>
          <Col xs="2">
            <MdAccountCircle size={60} />
          </Col>
        </Row>
      </Container>
    </div>
  )
}

export default Header
