import { NextPage } from 'next';
import { Col, Container, Row } from 'react-bootstrap';
import Image from 'next/image'
import  Head  from 'next/head';
import styles from '../styles/Home.module.css'
import { Button, TextField } from '@mui/material';


const Header: NextPage = () => {
    return (
        <div className="header">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/public/favicon.ico"/>
                <Container>
                    <Row>
                        <Col xs="3"  className="d-flex align-content-sm-start pt-2">
                            <div>
                                <div style={{backgroundColor: 'red'}}>
                                    <Image layout='fill' objectFit='cover' src='/images/logo-project.png' width='500' height='500'/>
                                </div>
                            </div>
                        </Col>
                        <Col xs="4"  className="d-flex justify-content-center pt-2">
                            <Row>
                                <Col>
                                    <TextField
                                        variant="standard"
                                    />
                                </Col>
                                <Col>
                                    <Button variant="contained">Copy</Button>
                                </Col>
                            </Row>

                        </Col>
                        <Col xs="2" className='pt-2'>
                            <p className='bg-success border rounded-pill'>test</p>
                        </Col>
                        <Col xs="2">
                            <p>test</p>
                        </Col>
                    </Row>
                </Container>
            </Head>
        </div>
    )
}

export default Header
