import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import Header from './header';
import SubFooter from './subfooter';

const Home: NextPage = () => {
    const [isRoomActive, setIsRoomActive] = useState(true);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header isRoomActive={isRoomActive} />
            <main className={styles.main}>

                <div className="container mx-0 mw-100" >

                    <div className="row">
                        <div className="col">
                            <div className={styles.landingText}>
                                <p>Discover a new voting system for your Poker Planning, with fun and innovative features.</p>
                                <p>No registration is required, just start a game and invite your colleagues to join you.</p>
                                <p>This application is Open Source and developed by 5th Floor teams. Discover the full story <a href='https://5thfloor.be/poker-fight'>here</a>.</p>
                            </div>
                        </div>
                    </div>

                    <div className="row">
                        <div className="offset-sm-3 col-sm-2 offset-1 col-10 my-1">
                            <button type="button" className="btn btn-primary w-100">CREATE ROOM</button>
                        </div>
                        <div className="offset-sm-2 col-sm-2 offset-1 col-10 my-1">
                            <button type="button" className="btn btn-success w-100">JOIN ROOM</button>
                        </div>
                    </div>
                </div>
            </main>
            {isRoomActive && <SubFooter />}
            <footer className={styles.footer}>

            </footer>
        </div>
    )
}

export default Home
